/**
 * Generate deployment shell script for MIP proposals
 */

/**
 * Generate the shell script for deploying the MIP proposal
 */
export function generateShellScript(mipNumber: number): string {
  return `#!/bin/bash
set -e

# MIP-X${mipNumber} Deployment Script
# Generated by moonwell-reward-automation

source .env

export PROPOSAL_NAME="MIP-X${mipNumber}"
export PROPOSAL_PATH="proposals/mips/mip-x${mipNumber}/x${mipNumber}.json"

echo "Deploying $PROPOSAL_NAME..."

# Run the forge script for rewards distribution
forge script proposals/templates/RewardsDistribution.sol \\
  --rpc-url $RPC_URL \\
  --broadcast \\
  --verify

echo "Deployment complete for $PROPOSAL_NAME"
`;
}
